### ISSUE TITLE
After Latest Plex update, MythRecordings doesn't work anymore

### ISSUE THREAD

**Issue by jbalcorn** [tschaumburg/MythRecordings.bundle#15]
I've been loving MythRecordings, but I installed latest Plex update and it won't play my videos anymore.  Every recording says "There was a problem playing this item".  I updated my MythRecordings code (I was way behind) and restarted Plex, but no luck.  Did Plex change something?  Is this fixable?  Or is it just my server?

Plex 0.9.16.0.1754 on Ubuntu 14.04

**Comment by ghost** [comment]
I was going to comment on the same issue on current Arch Linux:
Plex 0.9.16.0.1754 does not connect, reverting back to 0.9.15.6.1714 works fine again

Indeed, thanks for MythRecordings.bundle!! Wonderful having MythTV on the road

**Comment by Jim1Hurley** [comment]
I also have Plex and MythTV running on the same box, using Ubuntu 14.04  MythTvRecordings.bundle will work on the Chrome app, but fails on the Roku and Android apps.  I can't speak for iOS as I do not have the app to test.  I will happily downgrade my Plex Media Server to a 0.9.15 version unless there is a major security risk. 

Is this bundle still being updated?

**Comment by jbalcorn** [comment]
I hadn't tried on Chrome before, but I see the same symptoms.  Doesn't work
on Roku or Android, DOES with Chrome.

I've updated Plex, but no change.  plexmediaserver 0.9.16.3.1840-cece46d on
Ubuntu 14.04

Is there no chance that this is going to be fixed from either bundle author
or Plex team?

## 

Justin B. Alcorn
PGP Fingerprint A36D D691 C5B0 BE15 5A2A AF49 AA1C 372C

**Comment by ghost** [comment]
So it looks like there are other bundle applications that are experiencing similar problems with 0.9.16. On  another forum (sorry using phone hard to provide link) a mention was made of a bug in 0.9.16. Therefore this is most likely unrelated to this bundle. So the solution is to use 0.9.15 server until 0.9.16 is fixed. 

On a positive note.  This works perfect with MythTV 0.28 beta!!

**Comment by ghost** [comment]
This is now fixed.  I am running server version 0.9.16.4.1911 with current android Plex client. It looks like they fixed this at the client end of things.

**Comment by jbalcorn** [comment]
The client end of things is the MythRecordings bundle.  It hasn't been
updated.   It must have been fixed by the server update, which is good news.

## 

Justin B. Alcorn
PGP Fingerprint A36D D691 C5B0 BE15 5A2A AF49 AA1C 372C

**Comment by Jim1Hurley** [comment]
I can also verify that PMS update 0.9.16.4.1911-ee6e505 (April 5 2016)
fixes this issue.  MythTV recordings work again for the problem apps I
had.  Roku and Android.

**Comment by ghost** [comment]
@jbalcorn "The client end of things is the MythRecordings bundle"
Not really what I meant. To make this work again one needs a 0.9.16.4 based server version and up to date Plex for Android or Plex for Roku client.

**Comment by danpoltawski** [comment]
This seems to have stopped working again with 1.0.3.2461

**Comment by ghost** [comment]
Yup, this is stuck again which is a drag as I love the Plex-MythTV thing as much as like seeing my other media. I still have the working pre v1 Plex Server builds saved but I'm not sure it's a good idea to regress back that far.

**Comment by ghost** [comment]
Hey guys, good news. I got this working again. 

So I noticed this worked with web interface on localhost but nowhere else. I began to think it might have had to do with a security feature for streaming accross any type of network. When I added my MythTV recordings directory as an official Plex media library it worked no problem. (this action  includes  the mythtv recording  directory in Plex's watched folders and probably provides permission to stream) 

I'm not sure if the two recent Plex server updates have enabled anything as well but I have it working on newest 1.1.2.xxxx version 

EDIT: A few Caveat's:
1) It tested as fixed for Plex web and Plex Media Player. It's failing however on the Plex app for both android devices I have
2) If you don't want Plex server going mad trying to find movie metadata for the numbered MythTV file names, add the Mythtv directory as a Home Video type of library

**Comment by krbvroc1** [comment]
> This seems to have stopped working again with 1.0.3.2461

@danpoltawski - thanks for this. I came here before upgrading to see if there were any reports - I will hold off. I hope you will report if anything improves.

@wdirksen - Sorry, I cannot follow what you are saying. I use mythrecordings.bundle so that plex can stream files from my 0.27 backend. My plex server does not have access to any filesystem on the mythtv server. I use a plex roku client. If you are saying what I think you are, you are completely bypassing the plugin by directly access the files - so mythtv is not involved at all - that is really not a solution or a workaround. Am I understanding that correctly?

**Comment by ghost** [comment]
@krbvroc1 - The issue has been that the plugin refuses to stream the MythTV media it sees. Keeping all other factors constant, after adding the MythTV recording directory to Plex server as a media library, the plugin itself then does play media in Plex web client running Firefox and Chrome and in the new Plex Player; but not the Android app .

I realize this is a band-aid of sorts and is a form of functionality redundancy but it does work. Additionally it demonstrates that this is likely related to Plex's recent wave of security enhancements and not a fundamental incompatibility of the plugin to the currently updated Plex server as a whole.

BTW: How did you get the plugin up and running before if ... "My plex server does not have access to any filesystem on the mythtv server"?

**Comment by krbvroc1** [comment]
> BTW: How did you get the plugin up and running before if ... "My plex server does not have access to any filesystem on the mythtv server"?

The main point of this plugin is that it communicates with the mythtv backend to gather a list of recordings to give to the plex server.

If you goto
http://yourmythtvdevice:6544/Dvr/GetRecordedList
you will see a list of recordings - that is how the plugin populates the listings.
Each returned recording is an xml record and contains a ChanId and StartTime.
This plugin provides the playback URL to plex as
http://yourmythtvdevice:6544/Content/GetRecording?ChanId=X&StartTime=Y

So plex does not need any access to the filesystem because the VideoClipObject returned to plex via this plugin only contains the above http URL. So plex will then contact the mythtv backend directly to stream the file (and transcode it if needed).

What it sounds like you are doing is making the file avaialble on the plex server directly which bypasses all of this. At that point plex is providing its own list of recording based on the files present and when you playback it reads the file from disk rather than from the mythtv server.

**Comment by ghost** [comment]
@krbvroc1: Thanks for that.

It remains interesting that this plugin points to the mythbackend IP and nothing else. Yet the plugin itself works again if the same mythtv files are specified in the Plex media library.

**Comment by krbvroc1** [comment]
@wdirksen - Yes very odd indeed. I hope to have some time to look into it if no one else does.

**Comment by danpoltawski** [comment]
Update from me - it appears to be working again in Version 1.0.3.2461

Note: I did have to 'restart' the client app to get it to work.

**Comment by krbvroc1** [comment]
I just updated my plex server from 0.9.16.6-1993 to 1.0.3.2461 to give it a test. I was able to play MythTV recordings on a Roku Plex client. I also tried an Android app which worked fine (at least for the 1 minute trial period). And I tested with Chrome browser on a PC which worked fine. So I am not seeing any of the problems reported here at this time.

**Comment by jeffballard** [comment]
I'll note that at this time:

Plex Server: 1.1.4.2757
Plex Android App: 4.32.2.597 (same version on both devices)

Android: 7.0 works (Nexus 9 tablet)
Android: 6.0.1 does not work (Nexus 6 phone)
Web: works

**Comment by ghost** [comment]
@jeffballard: Thanks for that. The plot thickens . . .

I no longer have to add the myth recordings to a Plex library for web to work. I'm beginning to wonder if this was ever the case. Between the changes of server and clients versions I did toggle between them and could replicate the issue then.

I'm also on:
Plex Server: 1.1.4.2757
Plex Android App: 4.32.2.597 (also on all devices)

HTC Droid DNA - AOSP Android 5.11 does not work
Samsung SM-P905 (Note 12.2) Cyanogenmod 13.0 (Android 6.01) does not work

**Comment by ghost** [comment]
My Samsung SM-P905 tablet just got upgraded to CM 14.1 which is based on Android Nougat 7.1. MythRecording channel now works on this device with Android Plex app. Still wont work on my Android 5.1 phone.

PMS ver: 1.3.0.3059-6277334
Plex Android App ver: 5.1.4.365

**Comment by ghost** [comment]
Geez this remains flaky; or recently outright broken on recent Plex Server versions. I'm tired of it.
Does anyone still have plexmediaserver-1.0.2.2413.7caf41d.x86_64.rpm in their machine? 

Plex have taken down all older versions from their downloads. The download links from previous versions are dead and diverted to current. I've been scouring the internet for archives to no avail. I need version 1.0.2 or earlier to be truly compatible with this excellent mythTV Plex plugin

Thanks..

**Comment by Jim1Hurley** [comment]
Personally, I don't have any .rpm files.  I have quite a few older X64 .deb
(Ubuntu) files, including the 1.0.2.2413.7, but again, no .rpm

**Comment by Jim1Hurley** [comment]
I mainly use the MythRecordings bundle on my Roku.  Even with the newest
version of PMS the MythRecordings bundle works with the plexclassic app.
It's a pain having to use a separate Roku app, but for me it's worth it.

https://my.roku.com/account/add?channel=plexclassic

**Comment by ghost** [comment]
Thanks Jim. The newer server versions have worked on the web app but never reliably for Android. I'll check out the Roku link. I have an old Roku M1000, their original product, laying around somewhere but have not followed what Roku are up to.

The .deb version will work fine as my server is actually Arch Linux and either container will decompress and work fine. I would love to try the 1.0.2.2413 version again.  Do you have suggestions on how to post it? I really appreciate the friendly gesture. I will be travelling in a few weeks and don't want to miss the recorded races, etc.

**Comment by Jim1Hurley** [comment]
Good Luck!  remember it's a 64 Bit version.  I'm deleting the link in 24
hours.

https://www.dropbox.com/s/0j43ipbrsa22yiz/plexmediaserver_1.0.2.2413-
7caf41d_amd64.deb?dl=0

**Comment by ghost** [comment]
Perfect. Thanks alot. I've got it so you can delete it now.
I'm now a bit worried that it still won't work with current Plex android versions. Giving it a go..

**Comment by Jim1Hurley** [comment]
I deleted the link.  I can offer another pms download if that doesn't work.

**Comment by ghost** [comment]
Thanks for your help. I have PMS version 1.0.2 you sent running as I type however still no luck with android and the mythTV plugin. I know that PMS v1.0.2 was working well with this at one time but since then there have been numerous android app updates as well. I'm going to call it off now now

**Comment by krbvroc1** [comment]
I am running Plex 1.1.4.2757 and it works fine with the Android app.

**Comment by Jim1Hurley** [comment]
I have the 1.1.4.2757 .deb file also if you think it's worth your time.
Who knows if the next android update breaks it though.  Your call...

**Comment by tgourley01** [comment]
I updated Plex plugin to 1.5.5.3634 on FreeNAS-9.10.2-U1 and the plugin is no longer working.
I keep getting "there was a problem playing this item" and in the logs:
ERROR - downloadContainer: expected MediaContainer element, found Response...
ERROR - TranscodeUniversalRequest: unable to get container:...

Does anyone have a good resource for debugging the python code? I'm more than willing to help debug/support this plugin but all I've found is debugging via log files. There has to be a way to debug this.

**Comment by benjammin2068** [comment]
Update on Plex Media Server 1.6.1.3722 (CentOS 6.9 64bit)

Still broken.

looks like Plex changed something in one of their python modules. I have some good debug output both from the server and the plug-in. Should I just drop them here? 

The failure (in short) seems to be caused by:

```
2017-05-22 14:44:31,375 (7f848f63b700) :  DEBUG (runtime:717) - Handling request GET /video/mythrecordings/GetRecordingList?filterKeyName=Title&filterKeyValue=Bull&sortKeyName=StartTime
2017-05-22 14:44:31,379 (7f848f63b700) :  DEBUG (runtime:814) - Found route matching /video/mythrecordings/GetRecordingList
2017-05-22 14:44:31,379 (7f848f63b700) :  INFO (__init__:71) - GetRecordingList(filterKeyName="Title", filterKeyValue="Bull", sortKeyName="StartTime"): Loading URL http://127.0.0.1:6544/Dvr/GetRecordedList
2017-05-22 14:44:34,246 (7f848f63b700) :  INFO (__init__:181) - Recording: Name "Bull" => URL="http://127.0.0.1:6544/Content/GetFile?StorageGroup=Default&FileName=2031_20170517010000.ts"
2017-05-22 14:44:34,250 (7f848f63b700) :  INFO (__init__:181) - Recording: Name "Bull" => URL="http://127.0.0.1:6544/Content/GetFile?StorageGroup=Default&FileName=2031_20170510010000.ts"
2017-05-22 14:44:34,254 (7f848f63b700) :  INFO (__init__:181) - Recording: Name "Bull" => URL="http://127.0.0.1:6544/Content/GetFile?StorageGroup=Default&FileName=2031_20170503010000.ts"
2017-05-22 14:44:34,257 (7f848f63b700) :  INFO (__init__:181) - Recording: Name "Bull" => URL="http://127.0.0.1:6544/Content/GetFile?StorageGroup=Default&FileName=2031_20170426010000.ts"
2017-05-22 14:44:34,259 (7f848f63b700) :  INFO (__init__:181) - Recording: Name "Bull" => URL="http://127.0.0.1:6544/Content/GetFile?StorageGroup=Default&FileName=2031_20170419010000.ts"
2017-05-22 14:44:34,262 (7f848f63b700) :  INFO (__init__:181) - Recording: Name "Bull" => URL="http://127.0.0.1:6544/Content/GetFile?StorageGroup=Default&FileName=2031_20170405010000.ts"
2017-05-22 14:44:34,265 (7f848f63b700) :  INFO (__init__:181) - Recording: Name "Bull" => URL="http://127.0.0.1:6544/Content/GetFile?StorageGroup=Default&FileName=2031_20170329010000.ts"
2017-05-22 14:44:34,269 (7f848f63b700) :  INFO (__init__:181) - Recording: Name "Bull" => URL="http://127.0.0.1:6544/Content/GetFile?StorageGroup=Default&FileName=2031_20170308020000.ts"
2017-05-22 14:44:34,274 (7f848f63b700) :  INFO (__init__:181) - Recording: Name "Bull" => URL="http://127.0.0.1:6544/Content/GetFile?StorageGroup=Default&FileName=2031_20170215020000.ts"
2017-05-22 14:44:34,277 (7f848f63b700) :  INFO (__init__:181) - Recording: Name "Bull" => URL="http://127.0.0.1:6544/Content/GetFile?StorageGroup=Default&FileName=2031_20170208020000.ts"
2017-05-22 14:44:34,280 (7f848f63b700) :  INFO (__init__:181) - Recording: Name "Bull" => URL="http://127.0.0.1:6544/Content/GetFile?StorageGroup=Default&FileName=2031_20170201030000.ts"
2017-05-22 14:44:34,283 (7f848f63b700) :  INFO (__init__:181) - Recording: Name "Bull" => URL="http://127.0.0.1:6544/Content/GetFile?StorageGroup=Default&FileName=2031_20170125020000.ts"
2017-05-22 14:44:34,286 (7f848f63b700) :  INFO (__init__:181) - Recording: Name "Bull" => URL="http://127.0.0.1:6544/Content/GetFile?StorageGroup=Default&FileName=2031_20170118020000.ts"
2017-05-22 14:44:34,291 (7f848f63b700) :  INFO (__init__:181) - Recording: Name "Bull" => URL="http://127.0.0.1:6544/Content/GetFile?StorageGroup=Default&FileName=2031_20170104020000.ts"
2017-05-22 14:44:34,293 (7f848f63b700) :  INFO (__init__:181) - Recording: Name "Bull" => URL="http://127.0.0.1:6544/Content/GetFile?StorageGroup=Default&FileName=2031_20161214020000.ts"
2017-05-22 14:44:34,295 (7f848f63b700) :  INFO (__init__:181) - Recording: Name "Bull" => URL="http://127.0.0.1:6544/Content/GetFile?StorageGroup=Default&FileName=2031_20161207020000.ts"
2017-05-22 14:44:34,300 (7f848f63b700) :  INFO (__init__:181) - Recording: Name "Bull" => URL="http://127.0.0.1:6544/Content/GetFile?StorageGroup=Default&FileName=2031_20161102010000.ts"
2017-05-22 14:44:34,303 (7f848f63b700) :  INFO (__init__:181) - Recording: Name "Bull" => URL="http://127.0.0.1:6544/Content/GetFile?StorageGroup=Default&FileName=1912_20161026010000.ts"
2017-05-22 14:44:34,306 (7f848f63b700) :  INFO (__init__:181) - Recording: Name "Bull" => URL="http://127.0.0.1:6544/Content/GetFile?StorageGroup=Default&FileName=1912_20161019010000.ts"
2017-05-22 14:44:34,309 (7f848f63b700) :  INFO (__init__:181) - Recording: Name "Bull" => URL="http://127.0.0.1:6544/Content/GetFile?StorageGroup=Default&FileName=1912_20160928010000.ts"
2017-05-22 14:44:34,311 (7f848f63b700) :  INFO (__init__:181) - Recording: Name "Bull" => URL="http://127.0.0.1:6544/Content/GetFile?StorageGroup=Default&FileName=1004_20160920200000.nuv"
2017-05-22 14:44:34,321 (7f848f63b700) :  WARNING (objectkit:208) - Media part has no streams - attempting to synthesize
2017-05-22 14:44:34,343 (7f848f63b700) :  DEBUG (runtime:88) - Sending packed state data (120 bytes)
2017-05-22 14:44:34,343 (7f848f63b700) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 23142 bytes
2017-05-22 14:44:36,584 (7f848f63b700) :  DEBUG (runtime:717) - Handling request GET /video/mythrecordings/GetRecordingInfo?chanId=2031&startTime=2017-05-17T01%3A00%3A00Z&includeBandwidths=1
2017-05-22 14:44:36,588 (7f848f63b700) :  DEBUG (runtime:814) - Found route matching /video/mythrecordings/GetRecordingInfo
2017-05-22 14:44:36,589 (7f848f63b700) :  CRITICAL (runtime:889) - Exception (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-4955e31cf/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 843, in handle_request
    result = f(**d)
TypeError: RecordingInfo() got an unexpected keyword argument 'includeBandwidths'

2017-05-22 14:44:36,592 (7f848f63b700) :  DEBUG (runtime:88) - Sending packed state data (120 bytes)
2017-05-22 14:44:36,592 (7f848f63b700) :  DEBUG (runtime:924) - Response: [500] 506 bytes
2017-05-22 14:44:36,831 (7f848f63b700) :  DEBUG (runtime:717) - Handling request GET /video/mythrecordings/GetRecordingInfo?chanId=2031&startTime=2017-05-17T01%3A00%3A00Z&includeBandwidths=1
2017-05-22 14:44:36,834 (7f848f63b700) :  DEBUG (runtime:814) - Found route matching /video/mythrecordings/GetRecordingInfo
2017-05-22 14:44:36,835 (7f848f63b700) :  CRITICAL (runtime:889) - Exception (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-4955e31cf/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 843, in handle_request
    result = f(**d)
TypeError: RecordingInfo() got an unexpected keyword argument 'includeBandwidths'

2017-05-22 14:44:36,837 (7f848f63b700) :  DEBUG (runtime:88) - Sending packed state data (120 bytes)
2017-05-22 14:44:36,838 (7f848f63b700) :  DEBUG (runtime:924) - Response: [500] 506 bytes
2017-05-22 14:44:37,065 (7f848f63b700) :  DEBUG (runtime:717) - Handling request GET /video/mythrecordings/GetRecordingInfo?chanId=2031&startTime=2017-05-17T01%3A00%3A00Z
2017-05-22 14:44:37,067 (7f848f63b700) :  DEBUG (runtime:814) - Found route matching /video/mythrecordings/GetRecordingInfo
2017-05-22 14:44:37,068 (7f848f63b700) :  INFO (__init__:250) - RecordingInfo(chanId="2031", startTime="2017-05-17T01:00:00Z"): opening http://127.0.0.1:6544/Dvr/GetRecorded?StartTime=2017-05-17T01:00:00Z&ChanId=2031
2017-05-22 14:44:37,081 (7f848f63b700) :  INFO (__init__:181) - Recording: Name "Bull" => URL="http://127.0.0.1:6544/Content/GetFile?StorageGroup=Default&FileName=2031_20170517010000.ts"
2017-05-22 14:44:37,085 (7f848f63b700) :  DEBUG (runtime:88) - Sending packed state data (120 bytes)
2017-05-22 14:44:37,086 (7f848f63b700) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 1462 bytes
```

**Comment by benjammin2068** [comment]
I saw this comment on Plex -- so I applied changed suggested here to my init.py file (don't forget the underscores!) in the Myth plugin /code folder.

I went from:

`(line 247) def RecordingInfo(chanId, startTime):`

to:

`def RecordingInfo(chanId, startTime, seriesInetRef = None, checkFiles = 0, includeBandwidths = 0):`

and it works.

See: https://forums.plex.tv/discussion/86644/rel-mythtv-plug-in/p20

and it works.

**Comment by tgourley01** [comment]
Yes, that is working for me:
https://github.com/tgourley01/MythRecordings.bundle/commit/5816b372c3d0cc24ddee215dfdaf039f03bd6bca

**Comment by krisbee** [comment]
`includeBandwidths = 0` did not work for me... I had to change it to:  `includeBandwidths = None` on my system.  Though I do believe it is always transcoding now when I use my Roku app.

**Comment by tgourley01** [comment]
The latest freenas plugin update (plex 1.10.1.4602) broke this again.
This fix is working for me: 
https://github.com/tgourley01/MythRecordings.bundle/commit/6d73b7db7972d858ae637037dd3fdea3588118fc

**Comment by ghost** [comment]
@tgourley01, Man you rock! Thanks for actively maintaining your fork and keeping this plugin alive. Saved our vacation.

**Comment by krisbee** [comment]
Using 1.13.5.5291 and still get the "This Plugin is Not Responding"

This is what the logs say:
`Aug 03, 2018 18:06:20.082 [0x7efc62fff700] DEBUG - Auth: authenticated user 1 as USER
Aug 03, 2018 18:06:20.082 [0x7efc4effe700] DEBUG - Request: [127.0.0.1:53280 (Loopback)] GET /video/mythrecordings/GetRecordingList?staticBackground=by-date-background.png&sortKeyName=StartTime (5 live) GZIP Signed-in Token (USER)
Aug 03, 2018 18:06:20.082 [0x7efc4effe700] DEBUG - Plug-in dk.schaumburg-it.plexapp.mythrecordings has been used 8 times.
Aug 03, 2018 18:06:20.082 [0x7efc4effe700] DEBUG - [dk.schaumburg-it.plexapp.mythrecordings] Sending command over HTTP (GET): /video/mythrecordings/GetRecordingList?staticBackground=by-date-background.png&sortKeyName=StartTime
Aug 03, 2018 18:06:20.082 [0x7efc4effe700] DEBUG - HTTP requesting GET http://127.0.0.1:37561/video/mythrecordings/GetRecordingList?staticBackground=by-date-background.png&sortKeyName=StartTime
Aug 03, 2018 18:06:20.298 [0x7efc4effe700] DEBUG - HTTP 500 response from GET http://127.0.0.1:37561/video/mythrecordings/GetRecordingList?staticBackground=by-date-background.png&sortKeyName=StartTime
Aug 03, 2018 18:06:20.299 [0x7efc4effe700] DEBUG - [dk.schaumburg-it.plexapp.mythrecordings] HTTP reply status 500, with 671 bytes of content.
Aug 03, 2018 18:06:20.299 [0x7efc62fff700] DEBUG - Completed: [127.0.0.1:53280] 500 GET /video/mythrecordings/GetRecordingList?staticBackground=by-date-background.png&sortKeyName=StartTime (5 live) GZIP 217ms 955 bytes (pipelined: 6)
Aug 03, 2018 18:06:27.620 [0x7efc627fe700] DEBUG - handleStreamRead code 2: End of file
Aug 03, 2018 18:06:27.627 [0x7efc62fff700] DEBUG - Auth: authenticated user 1 as USER
Aug 03, 2018 18:06:27.627 [0x7efc4e7fd700] DEBUG - Request: [127.0.0.1:53280 (Loopback)] GET /player/proxy/poll?deviceClass=pc&protocolVersion=1&protocolCapabilities=timeline%2Cplayback%2Cnavigation%2Cmirror%2Cplayqueues&timeout=1 (4 live) GZIP Signed-in Token (USER)
Aug 03, 2018 18:06:27.627 [0x7efc4e7fd700] DEBUG - Beginning read from two-way stream.`


If I run the http line in question, this is the error that actually comes back:
`<Response code="2000" status="NameError: global name 'USE_PAGING' is not defined">
<Traceback>
Traceback (most recent call last): File "/usr/lib/plexmediaserver/Resources/Plug-ins-6fa5e50a8/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 843, in handle_request result = f(**d) File "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/MythRecordings.bundle/Contents/Code/__init__.py", line 514, in GetRecordingList if USE_PAGING and len(oc) >= MAX_EPISODES_PER_PAGE: NameError: global name 'USE_PAGING' is not defined
</Traceback>
</Response>`

**Comment by krisbee** [comment]
Okay, I figured out MY issue with Myth .29 otherwise known as Myth 29... Since Myth is no longer 0 point 29, this line fails (1012 and 1013)
`if major == 0 and minor < 27:`
`errors.append("Your MythTV server is version %s - this plugin is developed for version 0.27 and later" % version)`

Simply adding a hash to make it a comment fixed the issue for me... I don't know python (or git) enough to fix in the code here, so hopefully tschamburg can...
